service: service-core-citas

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  timeout: 30
  memorySize: 512
  lambdaHashingVersion: 20201221
  apiName: apiGateway-${self:provider.stage}
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    ENVIROMENT: ${self:provider.stage}
    DYNAMOTABLE: ${self:provider.stage}-CompletedOrderTable
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  hacerPedido:
    handler: src/handler.hacerPedido
    events:
      - http: 
          method: POST 
          path: /hacerPedido
  listarCita:
    handler: src/handler.listaCita
    events:
      - http: 
          method: GET 
          path: /cita/{id}
  listarCitas:
    handler: src/handler.listarCitas
    events:
      - http: 
          method: GET 
          path: /cita

resources:
  Resources:
    CompletedOrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMOTABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE